services:
  app:
    build: .
    container_name: vpn-app
##    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
      - /usr/bin/awg:/usr/bin/awg:ro
    environment:
      - DATABASE_URL=sqlite:///data/vpn.db
      - DEBUG=true
    command: >
      sh -c "
        python billing_sync.py boot &&
        python billing_sync.py fin &&
        python billing_sync.py tech &&
        ( 
          while true; do
          sleep 1800;
          python billing_sync.py fin;
          python billing_sync.py tech;
        done
        ) &
        uvicorn main:app --host 0.0.0.0 --port 5000
      "
    restart: unless-stopped
