services:
  app:
    build: .
    container_name: vpn-app
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
      - /usr/bin/awg:/usr/bin/awg:ro
    environment:
      - DATABASE_URL=sqlite:///data/vpn.db
      - DEBUG=false
    restart: unless-stopped